name: flutter_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  intl: ^0.19.0
  line_icons: ^2.0.3
  xml: ^6.5.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  meta: ^1.12.0
  transaction_repository:
    path: packages/transaction_repository
  flutter_speed_dial: ^7.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
