name: flutter_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  intl: ^0.19.0
  line_icons: ^2.0.3
  xml: ^6.5.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  meta: ^1.12.0
  flutter_animate: ^4.5.0
  firebase_repository:
    path: packages/firebase_repository
  widgets:
    path: packages/widgets
  mutual:
    path: packages/mutual
  carousel_slider: ^5.0.0
  firebase_auth: ^5.3.3
  receive_intent: ^0.2.7
  android_intent_plus: ^5.3.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/flags/
